# Mirror of frontend's DEFAULT_DEEPGRAM_KEYTERMS
# (frontend/src/hooks/useSpeechRecognition.js) — keep in sync manually,
# there is no shared source of truth between the two. Re-extract from the
# question_bank table whenever the question bank grows so this list keeps
# tracking real exam content, same as the frontend copy's own comment says.
DEEPGRAM_KEYTERMS: list[str] = [
    'RPA',
    'ITPA',
    'IT Process Automation',
    'Robotic Process Automation',
    'AutomationEdge',
    'AutomationEdge Server',
    'AutomationEdge Agent',
    'Process Studio',
    'SolFlows',
    'Active MQ',
    'GUI Spy',
    'Switch Case',
    'Filter Rows',
    'Formula step',
    'Rename Field',
    'Calculator step',
    'Start Browser',
    'clear browser instance',
    'locator',
    'XPath',
    'Web GUI automation',
    'singleton',
    'sequential',
    'assisted workflow',
    'unassisted',
    'Awaiting Input',
    'Execution Started',
    'Unload Project',
    'Load Project',
    'Export Project',
    'Import Project',
    'Publish',
    'Catalog',
    'ETL',
    'Extract Transform Load',
    'multi-threading',
    'digital worker',
    'workflow',
    'process',
    'orchestration',
]
