"""Add set_name to VivaSession

Revision ID: 30d87dee932b
Revises: 4bbf2ff29ebc
Create Date: 2026-08-26 12:21:06.616111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30d87dee932b'
down_revision: Union[str, Sequence[str], None] = '4bbf2ff29ebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'category',
               existing_type=postgresql.ENUM('USER_MANAGEMENT', 'SESSION_TRAINING', 'QUESTION_BANK', 'KNOWLEDGE_BASE', name='auditlogcategory'),
               nullable=False,
               existing_server_default=sa.text("'USER_MANAGEMENT'::auditlogcategory"))
    op.create_index('ix_audit_logs_category', 'audit_logs', ['category'], unique=False)
    op.add_column('viva_sessions', sa.Column('set_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viva_sessions', 'set_name')
    op.drop_index('ix_audit_logs_category', table_name='audit_logs')
    op.alter_column('audit_logs', 'category',
               existing_type=postgresql.ENUM('USER_MANAGEMENT', 'SESSION_TRAINING', 'QUESTION_BANK', 'KNOWLEDGE_BASE', name='auditlogcategory'),
               nullable=True,
               existing_server_default=sa.text("'USER_MANAGEMENT'::auditlogcategory"))
    # ### end Alembic commands ###
