"""add ideal_answer to question_bank

Revision ID: 4bbf2ff29ebc
Revises: d227c5deb505
Create Date: 2026-08-19 12:11:49.912516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bbf2ff29ebc'
down_revision: Union[str, Sequence[str], None] = 'd227c5deb505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_bank', sa.Column('ideal_answer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_bank', 'ideal_answer')
    # ### end Alembic commands ###
