"""remove unused columns

Revision ID: 88ecb53aea96
Revises: ca15db3b12fc
Create Date: 2026-08-18 11:57:36.073034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ecb53aea96'
down_revision: Union[str, Sequence[str], None] = 'ca15db3b12fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_module_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'module_id')
    op.drop_column('viva_questions', 'audio_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viva_questions', sa.Column('audio_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_module_id_fkey'), 'users', 'training_modules', ['module_id'], ['id'])
    # ### end Alembic commands ###
