"""Add audio_url to VivaQuestion

Revision ID: cd5889cab1be
Revises: 03ad2fcaf2d1
Create Date: 2026-08-31 11:49:32.518817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd5889cab1be'
down_revision: Union[str, Sequence[str], None] = '03ad2fcaf2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viva_questions', sa.Column('audio_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viva_questions', 'audio_url')
    # ### end Alembic commands ###
