"""add set_name to question_bank

Revision ID: d227c5deb505
Revises: 88ecb53aea96
Create Date: 2026-08-18 14:53:16.824756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd227c5deb505'
down_revision: Union[str, Sequence[str], None] = '88ecb53aea96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_bank', sa.Column('set_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_bank', 'set_name')
    # ### end Alembic commands ###
